Add AWS type request signer
opentelekomcloud/oms pull request #48
Opened 2020-10-15 11:21 UTC by anton-sidelnikov

Closes #3

2020-10-15 11:27 UTC, outcatcher requested changes
Please also add a functional test for authenticating with AK/SK

2020-10-15 11:27 UTC, outcatcher commented on src/oms/core/signer.ts
> +import * as Crypto from 'crypto-js';
Please don't use wildcard import if possible

2020-10-15 11:27 UTC, outcatcher commented on src/oms/core/signer.ts
> +export class SignatureInputData{
Class constructor is never used, can it be an interface?

2020-10-15 11:27 UTC, outcatcher commented on src/oms/core/signer.ts
>  //  CanonicalHeaders + '\n' +
Should this comment be here?

2020-10-15 11:28 UTC, anton-sidelnikov commented on src/oms/core/signer.ts
>  //  CanonicalHeaders + '\n' +
no

2020-10-15 11:31 UTC, lego963 commented on src/oms/core/signer.ts
> +        return algorithm + ' ' + 'Credential=' + input.accessKey + '/'
`'${algorithm } Credential=${input.accessKey }/${credentialScope }, SignedHeaders=${signedHeaders}, Signature=${signature}'`

2020-10-15 11:33 UTC, lego963 commented on src/oms/core/signer.ts
> +        return algorithm + ' ' + 'Credential=' + input.accessKey + '/'
https://basarat.gitbook.io/typescript/future-javascript/template-strings#string-interpolation

2020-10-15 18:45 UTC, outcatcher commented on src/oms/core/signer.ts
> +        serviceName: string): any
You can skip the return type definition for non-exported fields

2020-10-15 18:45 UTC, outcatcher commented on src/oms/core/signer.ts
> +    private static generateAuthorizationHeader(algorithm: string, input: SignatureInputData, credentialScope: string, signedHeaders: string, signature: any) {
Can `signature` really be `any`?

2020-10-15 18:45 UTC, outcatcher commented on src/oms/core/signer.ts
> +export interface SignatureInputData{
Interface fields can be readonly

2020-10-16 18:10 UTC, outcatcher commented on src/oms/index.ts
> +        const authData: SignatureInputData = {
You can skip type definition to make one less import

2020-10-16 19:07 UTC, lego963 commented on src/oms/core/signer.ts
> +    generateSignature(input: SignatureInputData, currentDate: Date = new Date()): SignatureOutputData {
`currentDate: Date = new Date()` has it be here?

2020-10-19 16:28 UTC, closed without merging